service: gpt-fastapi-backend

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  architecture: arm64

functions:
  api:
    handler: main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "https://www.interviewlab.dev"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.12:latest
    slim: true
